set nocompatible
filetype off

set rtp+=~/.dotfiles/vim/bundle/Vundle.vim/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Plugin 'gmarik/vundle'

" The bundles you install will be listed here
filetype plugin indent on

" The rest of your config follows here
Plugin 'bling/vim-airline'
set laststatus=2
