" Autoreload of .vimrc
autocmd! bufwritepost .vimrc source %

"set the map leader key
let mapleader=","

" Better copy & paste
set pastetoggle=<F3>
set clipboard=unnamed

" Prepare for plugins and vundle
set nocompatible
filetype off

set rtp+=~/.dotfiles/vim/bundle/Vundle.vim/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Plugin 'gmarik/vundle'

" The bundles you install will be listed here
filetype plugin indent on
syntax on

" The rest of your config follows here
Plugin 'bling/vim-airline'
set laststatus=2
set t_Co=256

Plugin 'davidhalter/jedi-vim'

Plugin 'scrooloose/nerdtree'
map <F2> :NERDTreeToggle<CR>

Plugin 'drmikehenry/vim-fontsize'
