if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
    __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
    source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

# Activate current folder's pipenv virtualenv
# or accept an explicit virtualenv name
workon() {
    if [ $# -eq 0 ]
    then
        source "$(pipenv --venv)/bin/activate"
    else
        source "$HOME/.virtualenvs/$1/bin/activate"
    fi
}

# Making virtualenv alias
mkvenv() {
    cd $HOME/.virtualenvs
    virtualenv "$@"
    cd -
    workon "$1"
}

# Automatic virtualenv sourcing
function auto_pipenv_shell {
    if [ ! -n "$VIRTUAL_ENV" ]; then
        if [ -f "Pipfile" ] ; then
            workon
        fi
    fi
}
function cd {
    builtin cd "$@"
    auto_pipenv_shell
}

export WORKON_HOME=$HOME/Envs
export PROJECT_HOME=$HOME/Documents/Projects
alias ls='ls -GFh'
alias ph="cd $PROJECT_HOME"
eval $(/usr/libexec/path_helper -s)

export JAVA_HOME=/Library/Java/JavaVirtualMachines/latest/Contents/Home
export AIRFLOW_HOME=$HOME/Documents/Projects/Python/airflow-tutorial/airflow
export PYTHONSTARTUP=$HOME/.pythonstartup.py
# export PYTHONSTARTUP=/Users/johannes/.pyenv/versions/work/lib/python3.7/site-packages/jedi/api/replstartup.py
# export PYTHONSTARTUP="$(python -m jedi repl)"

PATH="/usr/local/opt/tcl-tk/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.config/bin:$PATH"
PATH="$HOME/.composer/vendor/bin:$PATH"
PATH="/usr/local/opt/php/bin:$PATH"
PATH="/usr/local/opt/cython/bin:$PATH"
PATH="/usr/local/opt/node@8/bin:$PATH"
PATH="/usr/local/opt/sqlite/bin:$PATH"
PATH="/usr/local/opt/curl/bin:$PATH"
export PATH

#export SSLKEYLOGFILE=$HOME/sslkeys.log
export CPPFLAGS="-I/usr/local/opt/curl/include \
-I/usr/local/opt/openssl@1.1/include/ \
-I/usr/local/opt/node@8/include \
-I/usr/local/opt/sqlite/include \
-I/usr/local/opt/zlib/include \
-I/usr/local/opt/curl/include"

export LDFLAGS="-L/usr/local/opt/curl/lib \
-L/usr/local/opt/openssl@1.1/include/ \
-L/usr/local/opt/node@8/libi \
-L/usr/local/opt/sqlite/lib \
-L/usr/local/opt/zlib/lib \
-L/usr/local/opt/curl/lib"
auto_pipenv_shell

export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

export PATH="$HOME/.cargo/bin:$PATH"

# Customizations
POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv context dir vcs)
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_VIRTUALENV_BACKGROUND=red

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
# rust
export PATH="/usr/local/opt/qt/bin:$PATH"
