call plug#begin('~/.local/share/nvim/plugged')
" Use release branch
Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'davidhalter/jedi-vim'

" Powerline without python dependency
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'altercation/vim-colors-solarized'

" Auto pairs will match parenthesis brackets braces and quotes
Plug 'jiangmiao/auto-pairs'

" NERD tree will be loaded on the first invocation of NERDTreeToggle command
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

call plug#end()

" Source .vimrc again after changes
autocmd! bufwritepost .vimrc source %

" Airline configuration
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#formatter = 'default'
syntax enable
set background=light
colorscheme solarized

set relativenumber

" Remaps
map <F3> :NERDTreeToggle<CR>
map <Leader>\ <ESC>
map <Leader>n :set relativenumber!<CR>

" Command line fuzzy search
set rtp+=/usr/local/opt/fzf

let g:python3_host_prog = '/Users/johannes/.local/share/virtualenvs/jedi-g0sjJoel/bin/python'

" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()
" Navigate back and forth with TAB and S-TAB
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Use CR for completion of selection
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

