#!/bin/bash

function updatePrompt {
    # Styles
    GREEN='\[\033[0;32m\]'
    BLUE='\[\033[0;34m\]'
    RED='\[\033[0;31m\]'
    YELLOW='\[\033[0;33m\]'
    RESET='\[\033[0m\]'
    # Base prompt: \W = working dir
    PROMPT="\W"
    # Current Git repo
    if type "__git_ps1" > /dev/null 2>&1; then
        PROMPT="$PROMPT$(__git_ps1 "${GREEN}(%s)${RESET}")"
    fi
    # Current virtualenv
    if [[ $VIRTUAL_ENV != "" ]]; then
        # Strip out the path and just leave the env name
        PROMPT="$PROMPT${BLUE}(${VIRTUAL_ENV##*/})${RESET}"
    fi
    PS1="$PROMPT\$ "
}

export -f updatePrompt

export PROMPT_COMMAND='updatePrompt'
